password: ENC[AES256_GCM,data:5aeV,iv:Stdrzz6m26bL+8RP5/MtNru9ravLfYGVbffGTG5sS6I=,tag:c8fFusvteRNJiscRkgnb9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-04T22:58:46Z"
    mac: ENC[AES256_GCM,data:REhES4B6DIYUSdeZw2HZVEOoN4xBu4PmnqgogA9wXGwMCy1/QcMyJ2fWJciO4cmhsVYOf0tlIMYw0cCetarRI6v6s9ZhTRxpcpQdUwNBgIXBAWUYqZ+OZ7xfGVtGw/9GytbHibRAC7Tdkr806DG76wuHV349NaZcxzy8C87OAV0=,iv:4NNDs2YJMTxiv0AvfS7xH9WHdcVxUzcjw7I8Np5VM34=,tag:KEprTY3ZZqp/btY5hVx64A==,type:str]
    pgp:
        - created_at: "2024-05-04T22:58:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3GxmNiwEHO1AQv9EGHj7bmxha71ub6bDBnkp3QWN8GFlpugL8Zu5XBGwRHb
            9+0Cv6qPaCKjtfffWm3pc8IB8gOwTdYaDfPAAK5JhvNRD83J/QgbASmIULAC9svy
            QKwfXFVt4ih3H+YBHEIbIkL/6o4Kl24PlmiFjcU5NyAtzgowsTyXduvipc9bvkJ1
            R3lKF5InzDI1I0m314b/SyCfMQ3xW7Cp08Wt4KIOg6PR1wE3NB9GeYneATq6eGT+
            fNq+PN4K6H75b6HMRLQltVUN7TARJlISknMNFzmXpSbqlQtWBPPOIsICyB9UK/ZT
            bI/wMueOBOjcWSgkhCvgwAFyNLbcRnrpqldkKIJOf3TvrmsLcd83qJesNgnmcLxg
            lL7kDEM/oI0R4hjK4oaxjdATMWnpm71pnoaxlzugPFYIcJsqVdAfkLRoUeA081rG
            kXMrK0Fo6//0cY3ptMPR3AFrBfctyf14Q/SAdhsWzptQiT9KVL7u/KTmWdeOAMZM
            Tg7e92RWYQeesFrKCM2j0l4BzLn/uHqNI5ZRPlDA+zopgHhi34MogGU9bb6Fvenw
            Ms9KmM6AKMgYZO+oj1rIbBbdN/icNg25zIBDjyJ/ZPNGvxALH6uC6RAJTkFz0fld
            IQYioSLnrIA3NtuM6Zr7
            =tX7d
            -----END PGP MESSAGE-----
          fp: 71EBFC46090A0CF8632535968A1201191108EE7E
    unencrypted_suffix: _unencrypted
    version: 3.8.1
